"use client";
import { useEffect,useMemo,useState } from "react";
type Row={bounty:any;analysis:any};
export default function Home(){
  const [rows,setRows]=useState<Row[]>([]);const [user,setUser]=useState<any>(null);const [q,setQ]=useState("");const [min,setMin]=useState(0);const [mode,setMode]=useState<"verified"|"paid"|"all">("verified");const [loading,setLoading]=useState(true);const [msg,setMsg]=useState("");const [meta,setMeta]=useState<any>({verifiedCount:0,paidCount:0});
  async function load(){setLoading(true);setMsg("");const r=await fetch(`/api/bounties?q=${encodeURIComponent(q)}&minReward=${min}&mode=${mode}`,{cache:"no-store"});const j=await r.json();setRows(j.data||[]);setMeta(j);setLoading(false);if(j.error)setMsg(j.error)}
  useEffect(()=>{fetch("/api/me").then(r=>r.json()).then(j=>setUser(j.user));load()},[]);useEffect(()=>{if(!loading)load()},[mode]);
  const ranked=useMemo(()=>rows.filter(x=>x.analysis.estimatedHours.likely<=50),[rows]);
  async function action(id:string,a:string){const r=await fetch("/api/bounties/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({bountyId:id,action:a})});const j=await r.json();if(!r.ok){setMsg(j.error||"Action failed");return}if(a==="attempt"&&j.attempt?.id){window.location.href=`/attempts/${j.attempt.id}`;return}setMsg(`${a} saved`)}
  return <main className="shell"><aside><div className="brand">Bounty<span>OS</span></div><nav>{[["/","Dashboard"],["/bounties","Bounties"],["/saved","Saved"],["/attempts","My Attempts"],["/earnings","Earnings"],["/skills","Skills"],["/settings","Settings"]].map(([href,label],i)=><a className={i===0?"active":""} href={href} key={href}>{label}</a>)}</nav><div className="phase">BOUNTYOS<br/><b>HUNTER → SOLVER → EARNER</b></div></aside>
    <section className="content"><header><div><p className="eyebrow">AI BOUNTY OPERATING SYSTEM</p><h1>Find work that <em>pays.</em></h1><p className="muted">BountyOS separates verified paid work from ordinary GitHub issues and ranks the money-making opportunities first.</p></div>{user?<span className="user">@{user.username}</span>:<a className="github" href="/api/auth/github">Sign in with GitHub</a>}</header>
      <section className="stats"><Stat n={String(meta.verifiedCount??0)} label="Verified paid"/><Stat n={String(meta.paidCount??0)} label="Paid matches"/><Stat n={String(rows.filter(x=>x.analysis.opportunityScore>=70).length)} label="High opportunity"/></section>
      <div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search technology, issue, repository…"/><select value={min} onChange={e=>setMin(Number(e.target.value))}><option value="0">Any reward</option><option value="50">$50+</option><option value="100">$100+</option><option value="500">$500+</option><option value="1000">$1,000+</option></select><select value={mode} onChange={e=>setMode(e.target.value as any)}><option value="verified">💰 Verified paid only</option><option value="paid">🟡 Paid / verify</option><option value="all">⚪ All GitHub issues</option></select><button onClick={load}>Refresh</button></div>
      {msg&&<div className="notice">{msg}</div>}<div className="sectionHead"><div><p className="eyebrow">RANKED LIVE FEED</p><h2>🔥 Highest-value work</h2></div></div>
      {loading?<div className="empty">Discovering GitHub bounties, checking comments, and verifying reward evidence…</div>:ranked.length===0?<div className="empty"><b>No matching paid opportunities found.</b><br/><span className="muted">Try Paid / verify, lower the minimum reward, or search for a specific technology.</span></div>:<div className="cards">{ranked.slice(0,20).map(({bounty:b,analysis:a})=>{const verified=Boolean(b.signals?.rewardVerified);return <article className="card" key={b.id}><div className="cardTop"><div><span className="pill">{verified?"✓ VERIFIED PAID":b.reward.amount?"🟡 PAID — VERIFY":"OPEN ISSUE"}</span><h3>{b.issue.title}</h3><p className="repo">{b.repository.owner}/{b.repository.name} · #{b.issue.number} · {b.source}</p></div><strong>{b.reward.amount?`${b.reward.currency==="USD"?"$":b.reward.currency+" "}${b.reward.amount.toLocaleString()}`:"No reward"}</strong></div><div className="chips">{b.labels.slice(0,5).map((x:string)=><span key={x}>{x}</span>)}{verified&&<span>✓ {b.signals.rewardConfidence}% verified</span>}{b.signals?.rewardSource==="algora"&&<span>Algora</span>}</div><div className="metrics">{[["Difficulty",a.difficulty.replaceAll("_"," ")],["Effort",`${a.estimatedHours.minimum}–${a.estimatedHours.maximum}h`],["Success",`${a.successProbability}%`],["Acceptance",`${a.acceptanceProbability}%`],["Fit",`${a.technicalFit}%`],["Score",`${a.opportunityScore}/100`]].map(([l,v])=><div key={l}><span>{l}</span><b>{v}</b></div>)}</div><div className="why"><b>Why:</b> {a.reasons.join(" · ")}</div><div className="actions"><a href={b.sourceUrl} target="_blank">Issue ↗</a><button onClick={()=>action(b.id,"save")}>Save</button><button onClick={()=>action(b.id,"skip")}>Skip</button><button onClick={()=>action(b.id,"attempt")}>Start attempt</button></div></article>})}</div>}
    </section></main>}
function Stat({n,label}:{n:string,label:string}){return <div className="stat"><b>{n}</b><span>{label}</span></div>}
