import { GitHubBountySource } from "@/integrations/github/bounty-source";
import { buildAnalysis } from "@/lib/bounty/scoring";

export default async function Home() {
  let bounties: Awaited<ReturnType<GitHubBountySource["search"]>> = [];
  let error = "";
  try { bounties = await new GitHubBountySource().search(); } catch (e) { error = e instanceof Error ? e.message : "Unable to reach GitHub."; }
  const profile = { languages: ["TypeScript", "JavaScript"], frameworks: ["React", "Next.js", "Node.js"], databases: ["PostgreSQL"], level: "advanced" as const };
  const ranked = bounties.map((b) => ({ bounty: b, analysis: buildAnalysis(b, profile) })).sort((a, z) => z.analysis.opportunityScore - a.analysis.opportunityScore);
  return <main className="shell"><aside><div className="brand">Bounty<span>OS</span></div><nav><a className="active">Dashboard</a><a>Bounties</a><a>Saved</a><a>My Attempts</a><a>Earnings</a><a>Skills</a><a>Settings</a></nav><div className="phase">PHASE 1<br/><b>BOUNTY HUNTER</b></div></aside><section className="content"><header><div><p className="eyebrow">AI BOUNTY HUNTER</p><h1>Best opportunities <em>for you.</em></h1><p className="muted">Real GitHub issues ranked by expected successful return per hour.</p></div><button className="github">Sign in with GitHub</button></header><section className="stats"><Stat n={String(bounties.length)} label="Available"/><Stat n={String(ranked.filter(x=>x.analysis.opportunityScore>=70).length)} label="High opportunity"/><Stat n={String(ranked.slice(0,7).length)} label="Recommended"/></section>{error && <div className="notice">GitHub discovery unavailable: {error}. Add <code>GITHUB_TOKEN</code> for higher API limits.</div>}<div className="sectionHead"><div><p className="eyebrow">RANKED LIVE FEED</p><h2>🔥 Best opportunities for you</h2></div><button className="filter">Filters</button></div><div className="cards">{ranked.slice(0,12).map(({bounty,analysis})=><article className="card" key={bounty.id}><div className="cardTop"><div><span className="pill">{analysis.opportunityScore >= 80 ? "HIGH OPPORTUNITY" : "REVIEW"}</span><h3>{bounty.issue.title}</h3><p className="repo">{bounty.repository.owner}/{bounty.repository.name} · #{bounty.issue.number}</p></div><strong>{bounty.reward.amount ? `$${bounty.reward.amount.toLocaleString()}` : "Reward unclear"}</strong></div><div className="chips">{bounty.labels.slice(0,4).map(l=><span key={l}>{l}</span>)}</div><div className="metrics"><Metric label="Difficulty" value={analysis.difficulty.replaceAll("_"," ")}/><Metric label="Effort" value={`${analysis.estimatedHours.minimum}–${analysis.estimatedHours.maximum}h`}/><Metric label="Success" value={`${analysis.successProbability}%`}/><Metric label="Acceptance" value={`${analysis.acceptanceProbability}%`}/><Metric label="Fit" value={`${analysis.technicalFit}%`}/><Metric label="Score" value={`${analysis.opportunityScore}/100`}/></div><div className="why"><b>Why this score?</b> {analysis.reasons.join(" · ")}</div><div className="actions"><a href={bounty.sourceUrl} target="_blank">View issue ↗</a><button>Analyze</button><button>Save</button><button>Skip</button></div></article>)}</div>{!ranked.length && !error && <div className="empty">No bounty opportunities found yet. Try refreshing or broaden the discovery query.</div>}</section></main>
}
function Stat({n,label}:{n:string,label:string}){return <div className="stat"><b>{n}</b><span>{label}</span></div>}
function Metric({label,value}:{label:string,value:string}){return <div><span>{label}</span><b>{value}</b></div>}
